name: CI/CD

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
    
      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: https://github.com/docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: nucceteere/serverseekerv2-pyapi:latest